---
- name: Reload Nginx
  become: yes
  service:
    name: nginx
    state: reloaded

- name: Restart Nginx
  become: yes
  service:
    name: nginx
    state: restarted

- name: Reload PHP-FPM
  become: yes
  service:
    name: php7.4-fpm
    state: reloaded

- name: Restart PHP-FPM
  become: yes
  service:
    name: php7.4-fpm
    state: restarted
