# Work in progress!
# Currently having issues around Gems not being
# available during the post-receive hook.

- name: Install Git
  become: yes
  yum:
    name: git
    state: installed
    lock_timeout: 180

- name: Install Ruby
  become: yes
  command: amazon-linux-extras install -y ruby2.6
  args:
    creates: /usr/bin/ruby

- name: Install gcc, zlib, and ruby-devel (for building native Ruby gems)
  become: yes
  yum:
    name:
      - gcc
      - gcc-c++
      - zlib
      - zlib-devel
      - ruby-devel
    state: installed
    lock_timeout: 180

- name: Install github-pages Gem
  become: yes
  gem:
    name: "{{ item }}"
    state: latest
    user_install: no
  with_items:
    - bundler
    - github-pages

- name: "Ensure there is a /data directory owned by '{{ ansible_user }}'"
  become: yes
  file:
    path: /data
    state: directory
    recurse: yes
    owner: "{{ ansible_user }}"

- name: Ensure /data/git/gitdirs and /data/git/repos directories exist
  file:
    path: "/data/git/{{ item }}"
    state: directory
  with_items:
    - gitdirs
    - repos

- name: Create bare Git repo for {{ jekyll_autodeploy_repo }}.git
  command: git init --bare /data/git/repos/{{ jekyll_autodeploy_repo }}.git
  args:
    creates: /data/git/repos/{{ jekyll_autodeploy_repo }}.git/HEAD

- name: Create post-receive hook at {{ jekyll_autodeploy_repo }}.git to autodeploy Jekyll site
  template:
    src: post-receive.j2
    dest: /data/git/repos/{{ jekyll_autodeploy_repo }}.git/hooks/post-receive
    mode: a+x
  vars:
    baredir: /data/git/repos/{{ jekyll_autodeploy_repo }}.git
    gitdir: /data/git/gitdirs/{{ jekyll_autodeploy_repo }}
    apachedir: /var/www/{{ jekyll_autodeploy_destination }}
