---
- name: Check if wp-cli exists
  stat:
    path: "/usr/bin/wp"
  register: wpcli

- name: Update wp-cli
  become: yes
  shell: "/usr/bin/wp cli update --yes"
  when: wpcli.stat.exists

- name: Install wp-cli
  become: yes
  get_url:
    url: "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
    dest: "/usr/bin/wp"
    force_basic_auth: yes
    mode: 0755
  when: not wpcli.stat.exists

- name: Create production and staging databases
  become: yes
  mysql_db:
    name: "{{ item }}"
    state: present
  with_items:
    - production
    - staging

- name: Create wordpress mysql user
  become: yes
  mysql_user:
    name: "wordpress"
    password: "{{ wp_mysql_password }}"
    priv: "*.*:ALL"
