---
- hosts: cafe-laziz-backend
  # Get Github credentials for cloning repo
  vars_prompt: 
    - name: "githubuser" 
      prompt: "Enter your github username" 
      private: no 
    - name: "githubpassword" 
      prompt: "Enter your github password" 
      private: yes 
  roles:
    - name: cafe-laziz-backend
      tags: cafe-laziz-backend
